import type { Pedido, PedidoLoja, Sacola, SacolaLoja } from "./types";

export const sacolas: Sacola[] = [
  {
    id: "surpresa-doce",
    listingId: "surpresa-doce-l",
    nome: "Sacola Surpresa Doce",
    loja: "Domenica Casa de Pães",
    lojaId: "mock-domenica-casa-de-pães",
    lojaFotoUrl: null,
    distancia: "450m",
    emoji: "🥐",
    corThumb: "#FCEFE3",
    precoOriginal: 45,
    preco: 27.9,
    desconto: "38% off · última unidade",
    janela: "18h40 – 19h00",
    janelaNota: "Restam 18 minutos para o início da retirada",
    timer: "18 min",
    disponivel: 1,
    total: 8,
    janelaInicio: null,
    janelaFim: null,
    avaliacao: 4.8,
    avaliacoesTotal: 0,
    endereco: "Rua Padre Chagas, 314 — Bom Fim",
    descricao:
      "Uma seleção surpresa dos pães, croissants e doces que sobraram do dia na Domenica Casa de Pães. Tudo preparado nas últimas 24 horas — só não vendemos tudo antes do fechamento, e por isso o desconto é tão grande.",
    fotoUrl: null,
    alergenos: [],
    conteudos: [
      { emoji: "🥐", label: "Croissants amanteigados", tag: "Provável" },
      { emoji: "🍞", label: "Pão de fermentação natural", tag: "Provável" },
      { emoji: "🧁", label: "Mini bolos ou muffins", tag: "Possível" },
    ],
    categoria: "padaria",
    destaque: true,
  },
  {
    id: "almoco-do-dia",
    listingId: "almoco-do-dia-l",
    nome: "Sacola Almoço do Dia",
    loja: "Madrecita Bistrô",
    lojaId: "mock-madrecita-bistrô",
    lojaFotoUrl: null,
    distancia: "700m",
    emoji: "🥗",
    corThumb: "#E9F1E6",
    precoOriginal: 39,
    preco: 24.9,
    desconto: "36% off",
    janela: "14h30 – 15h00",
    janelaNota: "Restam 32 minutos para o fim da retirada",
    timer: "32 min",
    disponivel: 5,
    total: 6,
    janelaInicio: null,
    janelaFim: null,
    avaliacao: 4.7,
    avaliacoesTotal: 0,
    endereco: "Rua Fernandes Vieira, 512 — Bom Fim",
    descricao:
      "Uma seleção surpresa dos pratos do buffet do dia no Madrecita Bistrô. Comida caseira preparada hoje — o que não foi servido no almoço vira sacola com desconto.",
    fotoUrl: null,
    alergenos: [],
    conteudos: [
      { emoji: "🍛", label: "Prato executivo do dia", tag: "Provável" },
      { emoji: "🥗", label: "Salada da estação", tag: "Provável" },
      { emoji: "🍮", label: "Sobremesa da casa", tag: "Possível" },
    ],
    categoria: "refeicao",
  },
  {
    id: "mista-paes",
    listingId: "mista-paes-l",
    nome: "Sacola Mista Pães",
    loja: "Panificadora Estrela",
    lojaId: "mock-panificadora-estrela",
    lojaFotoUrl: null,
    distancia: "1,1km",
    emoji: "🍞",
    corThumb: "#F2E8DC",
    precoOriginal: 34,
    preco: 21.9,
    desconto: "35% off",
    janela: "18h00 – 19h00",
    janelaNota: "Retirada disponível até 19h00",
    timer: "até 19h",
    disponivel: 3,
    total: 6,
    janelaInicio: null,
    janelaFim: null,
    avaliacao: 4.6,
    avaliacoesTotal: 0,
    endereco: "Av. Osvaldo Aranha, 890 — Bom Fim",
    descricao:
      "Pães variados do dia na Panificadora Estrela: francês, integral, cacetinho e o que mais sobrar da fornada da tarde.",
    fotoUrl: null,
    alergenos: [],
    conteudos: [
      { emoji: "🥖", label: "Pães da fornada do dia", tag: "Provável" },
      { emoji: "🍞", label: "Pão integral ou de milho", tag: "Provável" },
      { emoji: "🥨", label: "Salgados de padaria", tag: "Possível" },
    ],
    categoria: "padaria",
  },
  {
    id: "frios-laticinios",
    listingId: "frios-laticinios-l",
    nome: "Sacola Frios e Laticínios",
    loja: "Mercado Zaffari Moinhos",
    lojaId: "mock-mercado-zaffari-moinhos",
    lojaFotoUrl: null,
    distancia: "1,4km",
    emoji: "🧀",
    corThumb: "#E7EEF5",
    precoOriginal: 54,
    preco: 34.9,
    desconto: "35% off",
    janela: "20h00 – 21h00",
    janelaNota: "Retirada disponível até 21h00",
    timer: "até 21h",
    disponivel: 2,
    total: 5,
    janelaInicio: null,
    janelaFim: null,
    avaliacao: 4.5,
    avaliacoesTotal: 0,
    endereco: "Rua 24 de Outubro, 1300 — Moinhos de Vento",
    descricao:
      "Queijos, iogurtes e frios próximos da data de validade, perfeitos para consumir nos próximos dias. Seleção surpresa do setor de laticínios.",
    fotoUrl: null,
    alergenos: [],
    conteudos: [
      { emoji: "🧀", label: "Queijos variados", tag: "Provável" },
      { emoji: "🥛", label: "Iogurtes e bebidas lácteas", tag: "Provável" },
      { emoji: "🥓", label: "Frios fatiados", tag: "Possível" },
    ],
    categoria: "mercado",
  },
];

export function getSacola(id: string): Sacola | undefined {
  return sacolas.find((s) => s.id === id);
}

// painel do parceiro (Domenica Casa de Pães)
export const sacolasLoja: SacolaLoja[] = [
  {
    id: "surpresa-doce",
    nome: "Sacola Surpresa Doce",
    emoji: "🥐",
    corThumb: "#E4EDE3",
    preco: 27.9,
    retiradaLabel: "Retirada 18h40 – 19h00",
    ativa: 1,
    reservada: 2,
    retirada: 1,
    naoRetirada: 0,
    receita: 27.9,
  },
  {
    id: "confeitaria",
    nome: "Sacola Confeitaria",
    emoji: "🧁",
    corThumb: "#E9F1E6",
    preco: 24.9,
    retiradaLabel: "Retirada 19h30 – 20h00",
    ativa: 5,
    reservada: 1,
    retirada: 0,
    naoRetirada: 0,
    receita: 0,
  },
  {
    id: "mista-paes",
    nome: "Sacola Mista Pães",
    emoji: "🍞",
    corThumb: "#F2E8DC",
    preco: 21.9,
    retiradaLabel: "Retirada até 19h00",
    ativa: 3,
    reservada: 4,
    retirada: 1,
    naoRetirada: 0,
    receita: 21.9,
  },
  {
    id: "manha",
    nome: "Sacola Manhã",
    emoji: "🥖",
    corThumb: "#F0EAE2",
    preco: 19.9,
    retiradaLabel: "Retirada concluída às 11h12",
    ativa: 0,
    reservada: 0,
    retirada: 5,
    naoRetirada: 0,
    receita: 99.5,
  },
  {
    id: "salgados",
    nome: "Sacola Salgados",
    emoji: "🥗",
    corThumb: "#F0EAE2",
    preco: 22.9,
    retiradaLabel: "Janela encerrada às 14h00",
    ativa: 0,
    reservada: 0,
    retirada: 2,
    naoRetirada: 1,
    receita: 68.7,
    alerta: true,
  },
];

export const pedidos: Pedido[] = [
  {
    id: "4827",
    codigo: "GF-4827",
    sacolaId: "surpresa-doce",
    nomeSacola: "Sacola Surpresa Doce",
    loja: "Domenica Casa de Pães",
    emoji: "🥐",
    data: "Hoje · retirada 18h40 – 19h00",
    qtd: 1,
    total: 27.9,
    status: "reservado",
  },
  {
    id: "4712",
    codigo: "GF-4712",
    sacolaId: "almoco-do-dia",
    nomeSacola: "Sacola Almoço do Dia",
    loja: "Madrecita Bistrô",
    emoji: "🥗",
    data: "28 de junho",
    qtd: 1,
    total: 24.9,
    status: "retirado",
  },
  {
    id: "4650",
    codigo: "GF-4650",
    sacolaId: "mista-paes",
    nomeSacola: "Sacola Mista Pães",
    loja: "Panificadora Estrela",
    emoji: "🍞",
    data: "21 de junho",
    qtd: 2,
    total: 43.8,
    status: "retirado",
  },
];

export function getPedido(id: string): Pedido | undefined {
  return pedidos.find((p) => p.id === id);
}

// pedidos recebidos pela Domenica Casa de Pães (visão do painel desktop)
export const pedidosLoja: PedidoLoja[] = [
  {
    id: "4827",
    codigo: "GF-4827",
    cliente: "Ana Beatriz M.",
    nomeSacola: "Sacola Surpresa Doce",
    emoji: "🥐",
    data: "Hoje",
    janela: "18h40 – 19h00",
    qtd: 1,
    total: 27.9,
    status: "reservado",
  },
  {
    id: "4831",
    codigo: "GF-4831",
    cliente: "Carlos Eduardo S.",
    nomeSacola: "Sacola Surpresa Doce",
    emoji: "🥐",
    data: "Hoje",
    janela: "18h40 – 19h00",
    qtd: 1,
    total: 27.9,
    status: "reservado",
  },
  {
    id: "4819",
    codigo: "GF-4819",
    cliente: "Juliana P.",
    nomeSacola: "Sacola Confeitaria",
    emoji: "🧁",
    data: "Hoje",
    janela: "19h30 – 20h00",
    qtd: 1,
    total: 24.9,
    status: "reservado",
  },
  {
    id: "4822",
    codigo: "GF-4822",
    cliente: "Rafael T.",
    nomeSacola: "Sacola Mista Pães",
    emoji: "🍞",
    data: "Hoje",
    janela: "até 19h00",
    qtd: 2,
    total: 43.8,
    status: "reservado",
  },
  {
    id: "4811",
    codigo: "GF-4811",
    cliente: "Fernanda L.",
    nomeSacola: "Sacola Mista Pães",
    emoji: "🍞",
    data: "Hoje",
    janela: "até 19h00",
    qtd: 2,
    total: 43.8,
    status: "reservado",
  },
  {
    id: "4805",
    codigo: "GF-4805",
    cliente: "Pedro H.",
    nomeSacola: "Sacola Surpresa Doce",
    emoji: "🥐",
    data: "Hoje",
    janela: "18h40 – 19h00",
    qtd: 1,
    total: 27.9,
    status: "retirado",
  },
  {
    id: "4801",
    codigo: "GF-4801",
    cliente: "Mariana C.",
    nomeSacola: "Sacola Mista Pães",
    emoji: "🍞",
    data: "Hoje",
    janela: "até 19h00",
    qtd: 1,
    total: 21.9,
    status: "retirado",
  },
  {
    id: "4788",
    codigo: "GF-4788",
    cliente: "Lucas G.",
    nomeSacola: "Sacola Manhã",
    emoji: "🥖",
    data: "Hoje",
    janela: "10h30 – 11h30",
    qtd: 2,
    total: 39.8,
    status: "retirado",
  },
  {
    id: "4790",
    codigo: "GF-4790",
    cliente: "Beatriz N.",
    nomeSacola: "Sacola Manhã",
    emoji: "🥖",
    data: "Hoje",
    janela: "10h30 – 11h30",
    qtd: 3,
    total: 59.7,
    status: "retirado",
  },
  {
    id: "4771",
    codigo: "GF-4771",
    cliente: "Gustavo R.",
    nomeSacola: "Sacola Salgados",
    emoji: "🥗",
    data: "Ontem",
    janela: "13h00 – 14h00",
    qtd: 2,
    total: 45.8,
    status: "retirado",
  },
  {
    id: "4769",
    codigo: "GF-4769",
    cliente: "Camila F.",
    nomeSacola: "Sacola Salgados",
    emoji: "🥗",
    data: "Ontem",
    janela: "13h00 – 14h00",
    qtd: 1,
    total: 22.9,
    status: "nao_retirado",
  },
  {
    id: "4744",
    codigo: "GF-4744",
    cliente: "Thiago M.",
    nomeSacola: "Sacola Surpresa Doce",
    emoji: "🥐",
    data: "15/07",
    janela: "18h40 – 19h00",
    qtd: 1,
    total: 27.9,
    status: "retirado",
  },
];
